version: '3.8'

services:
  frontend:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./frontend/public:/usr/share/nginx/html
      - ./frontend/src:/usr/share/nginx/html/src
      - ./nginx.conf:/etc/nginx/conf.d/default.conf 
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./backend
    expose:
      - "5000"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    volumes:
      - ./backend:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: money_tracker
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db_data:
