version: '3.5'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  zabbix-server:
    image: crpi-wi3zdg17u5fslig9.cn-shanghai.personal.cr.aliyuncs.com/dongdong024/zabbix-server:alpine-6.0-latest
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql
    ports:
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped

  zabbix-web:
    image: crpi-wi3zdg17u5fslig9.cn-shanghai.personal.cr.aliyuncs.com/dongdong024/zabbix-web:alpine-6.0-latest
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ZBX_SERVER_NAME: ${ZBX_SERVER_NAME}
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Asia/Shanghai
    depends_on:
      - mysql
      - zabbix-server
    ports:
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

volumes:
  mysql_data:
  grafana_data:
